# Generated by Django 3.2.6 on 2021-09-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_auto_20210909_1504'),
        ('recipe', '0002_auto_20210826_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='ingredient.Ingredient'),
        ),
    ]
