# Generated by Django 3.2.6 on 2021-09-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='datetime',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='expirey_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
